spring.application.name=Product
server.port=9093

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
#spring.datasource.url=jdbc:h2:mem:ProductDatabase
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create


spring.datasource.url=jdbc:postgresql://localhost:5432/ProductDatabase
spring.datasource.username=sa
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database = POSTGRESQL
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.jackson.time-zone=Asia/Kolkata

##spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:ecom-application}
##spring.datasource.username=${DATABASE_USERNAME:sa}
##spring.datasource.password=${DATABASE_PASSWORD:admin}
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
##spring.datasource.driver-class-name=org.postgresql.Driver
##spring.jpa.show-sql=${JPA_SHOW_SQL:true}
##spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
##spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
#
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
##management.endpoint.shutdown.enabled=true
